# Generated by Django 4.1 on 2022-08-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='foreign_images')),
                ('newly_released', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=300)),
                ('video', models.FileField(upload_to='foreign_videos')),
            ],
        ),
        migrations.CreateModel(
            name='LocalMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='local_images')),
                ('newly_released', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=300)),
                ('video', models.FileField(upload_to='local_videos')),
            ],
        ),
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_movies', models.ManyToManyField(to='customer.foreignmovies')),
                ('local_movies', models.ManyToManyField(to='customer.localmovies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
