# Generated by Django 4.1 on 2022-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignmovies',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='localmovies',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
